# Generated by Django 3.1.4 on 2021-02-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='InactiveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached_workspaces', models.ManyToManyField(related_name='apps', to='home.App')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.app')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=16)),
                ('field_label', models.TextField()),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long-text', 'Long Text'), ('number', 'Number'), ('url', 'Url'), ('choose-from-list', 'Choose from List'), ('date', 'Date'), ('rating', 'Rating'), ('instructions', 'Instructions')], default='text', max_length=250)),
                ('primary', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list', to='home.list')),
                ('select_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='select_list', to='home.list')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.list')),
            ],
        ),
        migrations.CreateModel(
            name='RecordRelation',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('relation_type', models.CharField(choices=[('choose-from-list', 'Choose from list'), ('embed', 'Embed'), ('tag', 'Tag')], default='active', max_length=25)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('child_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_record', to='home.record')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_field', to='home.listfield')),
                ('parent_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_record', to='home.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=home.models.record_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_of_file', models.CharField(default='', max_length=200)),
                ('file_extension', models.CharField(default='', max_length=200)),
                ('thumbnail_millisecond', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('I', 'Image'), ('V', 'Video'), ('F', 'File')], max_length=1)),
                ('thumbnail_source_image', models.ImageField(blank=True, null=True, upload_to='post_files/%Y/%m/%d/')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordField',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('value', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('list_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.listfield')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='home.record')),
                ('selected_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_record', to='home.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordComment',
            fields=[
                ('id', models.CharField(default='', editable=False, max_length=16, primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.record')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created', models.BooleanField(default=False)),
                ('can_access_all_apps', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='User', max_length=25)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.organization')),
                ('permitted_apps', models.ManyToManyField(to='home.App')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='active_users',
            field=models.ManyToManyField(through='home.OrganizationUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='inactive_users',
            field=models.ManyToManyField(to='home.InactiveUsers'),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=25)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='active', max_length=25)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.app')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='app_level_users',
            field=models.ManyToManyField(through='home.AppUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='app',
            name='inactive_users',
            field=models.ManyToManyField(to='home.InactiveUsers'),
        ),
        migrations.AddField(
            model_name='app',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.organization'),
        ),
    ]
