# Generated by Django 3.1.4 on 2021-02-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inactiveusers',
            name='attached_organizations',
        ),
    ]
