# Generated by Django 3.1.4 on 2021-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordfile',
            name='name_of_file',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(),
        ),
    ]
