# Generated by Django 3.1.4 on 2021-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210202_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmedia',
            name='name_of_file',
            field=models.CharField(default='', max_length=200),
        ),
    ]
