# Generated by Django 3.1.4 on 2021-02-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210202_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmedia',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'Image'), ('V', 'Video')], max_length=1),
        ),
    ]
