# Generated by Django 3.1.4 on 2021-02-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_recordmedia_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmedia',
            name='thumbnail_source_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_files/%Y/%m/%d/'),
        ),
    ]
