# Generated by Django 3.1.4 on 2021-02-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_recordmedia_thumbnail_source_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordmedia',
            name='thumbnail_millisecond',
            field=models.IntegerField(default=0),
        ),
    ]
